steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tienda-microservices-427201/auth-ms', '.']

artifacts:
  objects:
    location: 'gs://tienda-ms-bucket'
    paths: ['**']
options:
  logging: CLOUD_LOGGING_ONLY
